### ISSUE TITLE
Alarm trigger vs countdown issue

### ISSUE THREAD

**Issue by killervette42** [paulw11/homebridge-elkm1#11]
I am trying to have HomeKit turn on all the lights when my alarm goes off.  I tried the automation with “alarm” but it triggers when I enter my house before I enter my code to disable. Is there a dedicated alarm triggered state to use?

**Comment by daev1966** [comment]
I create a new automation based on when an accessory is controlled. Then select your Elk M1 in the list of accessories. Next select Triggers. After that select lights. 

I have my HomePod speakers throughout the house sound a siren alarm. It accesses the file from Apple Music.

**Comment by daev1966** [comment]
Hello,

I work for a security company north of Chicago Illinois for 20 years now. When the elk someone first came out in 2005 Wade Moose flew a group of us in his private jet to Hildebran for a tour of the officers and first training of the M1. The owner of my company has a close relationship with Wade and Kirk Phillips the current president of Elk.

My sole job now at Keyth has become servicing M1XEP ‘s. Using port forwarding and Jayson Calloways eKeypad for over a decade has been quite a nightmare. So many customers do not understand why their connection is lost when they change their routers. For the last year we have switched to only using M1 Cloud.

When Ness made their M1 - Automation Bridge Voice control Gateway I had hoped it was actually the same thing that your plug-in was capable of doing. It appears they have restricted it to only automation and not arming of the system. http://nesscorporation.com/ness-automation-1/ness-automation-modules/m1-specific-modules/101-296a.html<http://nesscorporation.com/ness-automation-1/ness-automation-modules/m1-specific-modules/101-296a.html>

I had first started using homebridge with the Elk plugin a couple years ago and was very happy although I had to frequently restart my homebridge.

Recently I reworked my homebridge setup completely using the new user interface and your plug-in. The reliability has been wonderful.

I think Elk Products and Ness Corporation should get together and pay you for your work.

Thank you so much for all you do.

Sent from my Keyth iPhone.

On Dec 10, 2020, at 4:33 PM, Paul Wilkinson <notifications@github.com> wrote:

﻿

Closed #11<https://github.com/paulw11/homebridge-elkm1/issues/11>.

**Comment by paulw11** [comment]
Thanks for the feedback David.

I created this plugin because I  wanted my own M1 integrated with HomeKit.  I am glad that other people find it useful.  Credit also needs to go to @SGentry since without their ElkMon package I would have had to do a lot more work.
