### ISSUE TITLE
Any plans on supporting multiple areas? Also would like option to exclude some things from auto load

### ISSUE THREAD

**Issue by lownotelee** [paulw11/homebridge-elkm1#13]
Some items that get autopopulated aren't needed in Home, so it'd be good to exclude them from the auto populate

**Comment by paulw11** [comment]
In version 2.0.0 only the configured zones are added to HomeKit.
You can also specify the tasks and outputs that you want to configure as HomeKit accessories
Multiple areas are supported by adding an additional M1 platform to your config with the same IP address and port
