### ISSUE TITLE
SyntaxError: Unexpected token =

### ISSUE THREAD

**Issue by RAGR1** [paulw11/homebridge-elkm1#2]
I was running Homebridge for my Nest thermostats. I tried adding the Elk M1 platform and now Homebridge won't start. It shows an error for the Elk M1 plugin and doesn't show anything for Nest anymore. Any help is appreciative.

-Added the Elk M1 info to my config.json (I'll paste it below) after it was validated in JSONLint.com.
-Ran "sudo npm install -g --unsafe-perm homebridge" and "sudo npm install -g --unsafe-perm homebridge-elkm1" in Terminal.
Ran "Homebridge" in Terminal and received the following:

[6/22/2017, 6:35:19 PM] Loaded plugin: homebridge-elkm1
/Users/Daddy/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-elkm1/node_modules/elkmon/dist/index.js:11
    constructor(port = 2101, host = '192.168.1.0', options = {
                     ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Plugin.module.exports [as initializer] (/Users/Daddy/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge-elkm1/index.js:21:11)
    at Server.<anonymous> (/Users/Daddy/.nvm/versions/node/v4.2.4/lib/node_modules/homebridge/lib/server.js:150:14)
    at Array.forEach (native)

Here's my config.json
{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "031-45-154"
	},

	"platforms": [{
		"platform": "Nest",
		"token": "c.5ABsTpo88k5yfNIxZlh...",
		"clientId": "db70f5a3-26bc-4c70-aa17-012035a3aa20",
		"clientSecret": "Yk9........d4",
		"code": "M42KH6PA",
		"username": "ra..@xxx.com",
		"password": "PasswordIsHere"
	}, {
		"platform": "ElkM1",
		"name": "ElkM1",
		"elkAddress": "192.168.xx.x"
		"elkPort": "2101",
		"area": "1",
		"keypadCode": "XXXX",
		"zoneTypes": {
			"1": "contact",
			"2": "garage",
			"3": "contact",
			"4": "contact",
			"5": "motion",
			"6": "motion",
			"7": "motion",
			"8": "motion",
			"9": "motion",
			"10": "motion",
			"16": "smoke"
		}
	}]
}

**Comment by paulw11** [comment]
You need to update your node.js instance.  The [elkmon](https://github.com/sgentry/elkmon) module that homebridge-elkm1 uses needs Node.js v6 or later.

**Comment by RAGR1** [comment]
Thank you. After uninstalling the old version of node.js, installing the new version, and reinstalling the Nest and Elk modules, everything looks to be working in HomeKit. Does this also allow Siri to control the alarm? 
Thank you for your help.

Robert

**Comment by paulw11** [comment]
Hi Robert,

I'm glad you got it working.

You can ask Siri something like "Set the alarm to stay" or "disarm the alarm"

**Comment by RAGR1** [comment]
That’s what I was trying but every time I say “alarm”, siri wants to set an alarm on my clock. I tried “security” and Siri says it cannot control a home security, so at least it’s understanding what I’m trying to do.

**Comment by paulw11** [comment]
It can be a little hit and miss.  You may have more success with "arm" and "disarm" rather than "set".  You can also use the name of your alarm zone rather than the generic "alarm", so "arm *myalarmname* to away"
