### ISSUE TITLE
Stopped working on iPhone 6 but still working on iPad

### ISSUE THREAD

**Issue by RAGR1** [paulw11/homebridge-elkm1#3]
I have not changed anything but the Home app works for Homekit enabled devices and returns a "No Response" for Homebridge accessories (Nest thermostats and Elk M1 alarm). All devices still work through Home app on iPad. Since I have not changed anything, I'm not even sure where to start looking...

**Comment by paulw11** [comment]
Since multiple homebridge plugins are affected, I doubt that it is anything to do with homebridge-elkm1.  Possibly the phone has an issue with the HomeKit sync.  I suggest you go into iCloud settings and turn "Home" off and on again and see if that helps.
