### ISSUE TITLE
Has anyone gotten it to Arm/Disarm?

### ISSUE THREAD

**Issue by kristiandg** [paulw11/homebridge-elkm1#47]
Good afternoon, all. Initially opened Issue #39 a little over a year ago, and no one's seemed to even respond to it. But, I can't get it to arm/disarm via HomeKit, nor can I get HomeKit to show the armed status if armed from the keypad.  It's as if it's not able to even see security-related status data, or isn't parsing it properly.  However, I see zone status changes and can execute commands to relays/outputs without issue.

Does anyone have any recommendations on how to fix the security component of this linkage? Two Areas built, but the one I care about is Area 1 (and that's what's configured currently).

Thanks.

**Comment by paulw11** [comment]
Duplicate #39
