### ISSUE TITLE
Error: Accessories must be created with a non-empty displayName

### ISSUE THREAD

**Issue by strobes99** [paulw11/homebridge-elkm1#5]
I am getting the following error when I try and load the ElkM1 plugin. It seems to be trying to load a blank accessory which I cannot seem to figure out where it is getting the blank from. Here is the startup and error:

[10/24/2017, 5:45:50 PM] [ElkM1] ***Connected***
[10/24/2017, 5:45:51 PM] [ElkM1] Initializing platform accessory 'Our House'...
[10/24/2017, 5:45:51 PM] [ElkM1] Initializing platform accessory ''...
(node:28509) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Accessories must be created with a non-empty displayName.
(node:28509) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I have tried various config.json including one with each zone defined in the elk and always get the same error. Here is the basic single zone config I used with no luck as well:
                {
                    "platform": "ElkM1",
                    "name": "ElkM1",
                    "elkAddress": "x.x.x.x",
                    "elkPort": "2101",
                    "area": "1",
                    "keypadCode": "xxxx",
                    "zoneTypes": {
                        "18": "garage"
                    },
                    "garageDoors":[
                    {
                        "stateZone":"18",
                        "openOutput":"11",
                        "closeOutput":"11",
                        "name":"Garage door"
                    }
                    ]
                },
Hopefully it is something simple that can be sorted out.

**Comment by paulw11** [comment]
Do you have more log information that shows the actual line in the homekit-elkm1 code where the error occurred.  It looks like you have a zone in your system that doesn't have a description.  I can modify the code to try and handle this, but the log information will help me confirm that I am fixing the right problem.

**Comment by strobes99** [comment]
After looking at the zones I did have several unused disabled zones that were blank. I made sure they all have a description and still got the error, then changed one that had an apostrophe in it and that seemed to get rid of the specific error, but now am getting the zs status report timeout error:

[10/24/2017, 7:02:49 PM] [ElkM1] Initializing ElkM1 platform...
[10/24/2017, 7:02:49 PM] [ElkM1] Connection is not secure
[10/24/2017, 7:02:49 PM] [ElkM1] Connecting to M1
[10/24/2017, 7:02:50 PM] [ElkM1] ***Connected***
(node:21143) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Timout occured before Zone Status Report (zs) was received.
(node:21143) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

That is all the info I get on this error, sorry to post this under the other heading, just trying to get this figured out. I checked the elkmon index.js and the timeout is at 15000 which seems to have fixed the other person's issues.

**Comment by strobes99** [comment]
Update, I was able to trace the problem to the point where it seems to be related to output names being blank. In the main index.js in this section of code I added a if statement to put something into a blank description and homebridge will now start normally and the alarm shows up as expected as do all the zones. Not sure if this will help you at all, but it at least got it to load for me and working....

	.then((outputText) => {
                   this.outputs = {};
                   for (var i = 0; i < outputText.length; i++) {
                     var td = outputText[i];
                      **if (td.description == "") {
                           td.description = "SOME DESCRIPTION";
                          }**
                        var output = new ElkOutput(Homebridge, this.log, this.elk, td.id, td.description);
                        this.outputs[td.id] = output;
                        this._elkAccessories.push(output);
                    }
                })

I tried making sure the first input had a description as well as output that is referenced in the config.json and that did not seem to make any difference.

**Comment by paulw11** [comment]
Yes, that helps.  
I'm glad you have a workaround.
I will release a fix shorty

**Comment by paulw11** [comment]
Fixed in 1.1.4
