### ISSUE TITLE
Limitations??

### ISSUE THREAD

**Issue by senadman** [paulw11/homebridge-elkm1#8]
Are there limitations to how many zones are supported. Reason i ask is my panel has 63zones, approx half motion and other half contact. When i enter them all into the config homebridge complains at start with:

(node:4412) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Accessories must be
created with a non-empty displayName.
(node:4412) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections
 that are not handled will terminate the Node.js process with a non-zero exit code.

When half the zones are entered approx 32 it works. Any ideas..

**Comment by paulw11** [comment]
There shouldn't be a limitation to the number of zones.  
The error message indicates that the zone is missing a name.

**Comment by senadman** [comment]
Yes for some reason one zone is coming through without a name although it is, I have removed it from the config and they load but like I said any more than 32 zones throws homebridge with a no response.

**Comment by paulw11** [comment]
I have just pushed version 1.1.5 to npm.  This has a check for  unconfigured zones.  It outputs an error and continues rather than crashing the initialisation.

**Comment by paulw11** [comment]
I decided to use a different approach, so 1.1.6 is now live

**Comment by senadman** [comment]
Due to the number of accessories i have accross all plugins i had to run homebridge over a few instances. Anyway, since doing that i can add all of my zones and the plugin works perfectly, other than two known issues:
1. An added accessory cannot be deleted in home app
2. Keep getting this error at random with different message received: 
[2018-5-18 03:16:12] [ElkM1] Error code received from elkmon: TypeError: The calculated checksum does not match the checksum on the received message: 1XK1214036180518011006C

**Comment by senadman** [comment]
Attempting to run this at startup on Mac OS with launchd. It starts the process but halts with an error : ENETUNREACH every time.

I have a couple of other plugins that require the network to be ready, these start at the same time and operate.

**Comment by paulw11** [comment]
The plugin now retries if connection fails
